import {
  authUser,
  chartOfAccounts,
  companies,
  expenses,
  invoices,
  journalEntries,
  journalLines,
  memberships,
} from '@thalermark/db';
import { eq, sql } from 'drizzle-orm';
import { v7 as uuidv7 } from 'uuid';
import { beforeAll, describe, expect, it } from 'vitest';
import { createApp } from '../src/app.js';
import type { Env } from '../src/env.js';
import { createApiAuth } from '../src/lib/auth.js';
import { createApiDatabase } from '../src/lib/db.js';
import { expensePostingLines, invoicePostingLines } from '../src/lib/ledger.js';
import { appDatabaseUrl, getTestDb, resetDb } from './test-helper.js';

// Reports at scale (TMC-188, item 3).
//
// Every report in routes/reports.ts is hand-written SQL over the general
// ledger, and until now none had been run against a book bigger than a test
// fixture. "It works" and "it works on 100,000 journal lines" are different
// claims, and only the second one matters to someone whose second year of
// trading is about to load a profit-and-loss.
//
// OPT-IN. Gated behind SCALE_TEST=1 so it never slows a PR — seeding is
// deliberately large and this is a tool for answering "did that change make
// reports slower?", not a per-commit gate. Committed rather than run once and
// thrown away, so the answer is reproducible:
//
//     SCALE_TEST=1 pnpm --filter @thalermark/api test reports-at-scale
//
// THE FIXTURE DOES NOT GO THROUGH THE API — that would take many minutes — but
// its LEDGER is generated by the real posting helpers (invoicePostingLines /
// expensePostingLines), the same pure functions the routes post through. This
// matters: a hand-written journal would measure a ledger shaped by this file's
// assumptions rather than by the code under test, and a posting-shape change
// would not show up here at all. scripts/seed-load-test.ts takes the same
// approach for the same reason — that script is the tool for seeding a real
// dev database by hand; this is the assertable, budgeted version.
//
// BUDGETS ARE DELIBERATELY GENEROUS. This is a regression detector, not a
// benchmark: the number that matters is "did this get 10x worse", not "is it
// 180ms or 240ms". A tight budget on shared CI hardware buys flakiness, and a
// flaky perf gate gets disabled within a month.

const SCALE = process.env.SCALE_TEST === '1';

// Roughly 100k journal lines: each invoice posts a 3-line entry (AR / revenue /
// tax) and each expense a 2-line entry.
const INVOICE_COUNT = Number(process.env.SCALE_INVOICES ?? 20_000);
const EXPENSE_COUNT = Number(process.env.SCALE_EXPENSES ?? 20_000);
const BUDGET_MS = Number(process.env.SCALE_BUDGET_MS ?? 5_000);

const testEnv: Env = {
  nodeEnv: 'test',
  port: 3000,
  logLevel: 'error',
  errorTrackingDsn: undefined,
  release: undefined,
  databaseUrl: '',
  appDatabaseUrl: '',
  appRolePassword: undefined,
  migrateOnBoot: false,
  betterAuthSecret: 'test-secret-at-least-32-characters-long',
  betterAuthUrl: 'http://localhost:3000',
  trustedOrigins: [],
  publicAppUrl: 'http://localhost:5173',
  resendApiKey: undefined,
  emailFrom: 'Thalermark <test@thalermark.test>',
  stripeSecretKey: undefined,
  stripePublishableKey: undefined,
  stripeWebhookSecret: undefined,
  recurringSweepCron: '0 6 * * *',
};

function extractSessionCookie(res: Response): string {
  const list =
    (res.headers as { getSetCookie?: () => string[] }).getSetCookie?.() ??
    [res.headers.get('set-cookie') ?? ''].filter(Boolean);
  return list.map((c) => c.split(';')[0]).join('; ');
}

function buildApp() {
  const url = process.env.DATABASE_URL;
  if (!url) throw new Error('DATABASE_URL not set');
  const handle = createApiDatabase(appDatabaseUrl());
  const auth = createApiAuth(getTestDb(), { ...testEnv, databaseUrl: url });
  return {
    handle,
    app: createApp({
      auth,
      db: handle.db,
      bootstrapDb: getTestDb(),
      publicAppUrl: testEnv.publicAppUrl,
    }),
  };
}

// Bulk fixture. One statement per table, generate_series doing the work in
// Postgres rather than shipping 100k round-trips from Node.
async function seedLargeBook(accountId: string, companyId: string) {
  const db = getTestDb();

  // A few hundred customers, so sales-by-customer has something to group.
  await db.execute(sql`
    INSERT INTO contacts (id, account_id, company_id, name, created_at, updated_at)
    SELECT gen_random_uuid(), ${accountId}, ${companyId}, 'Customer ' || g,
           now() - (g || ' days')::interval, now()
    FROM generate_series(1, 200) g
  `);

  // Invoices spread across 2026 so the date-windowed reports have real spread
  // and the month buckets are populated.
  await db.execute(sql`
    INSERT INTO invoices (
      id, account_id, company_id, contact_id, number, status,
      issue_date, due_date, currency, subtotal, tax, total, created_at, updated_at
    )
    SELECT
      gen_random_uuid(), ${accountId}, ${companyId},
      (SELECT id FROM contacts WHERE company_id = ${companyId} OFFSET (g % 200) LIMIT 1),
      'INV-' || g,
      CASE WHEN g % 7 = 0 THEN 'paid' ELSE 'sent' END,
      (DATE '2026-01-01' + ((g % 350) || ' days')::interval)::date,
      (DATE '2026-01-31' + ((g % 350) || ' days')::interval)::date,
      'USD', 100.00, 8.25, 108.25,
      now(), now()
    FROM generate_series(1, ${INVOICE_COUNT}) g
  `);

  // One line each, alternating service / product so the revenue split and
  // top-products both have data.
  await db.execute(sql`
    INSERT INTO invoice_line_items (
      id, account_id, invoice_id, position, description, quantity,
      unit_price, amount, type, taxable, tax_rate_pct, tax_amount, created_at, updated_at
    )
    SELECT gen_random_uuid(), ${accountId}, i.id, 1, 'Work', 1,
           100.0000, 100.00,
           CASE WHEN row_number() OVER () % 2 = 0 THEN 'product' ELSE 'service' END,
           true, 8.2500, 8.25, now(), now()
    FROM invoices i WHERE i.company_id = ${companyId}
  `);

  // Expenses across the same window.
  await db.execute(sql`
    INSERT INTO expenses (
      id, account_id, company_id, category_account_id, payment_account_id,
      amount, expense_date, merchant, created_at, updated_at
    )
    SELECT
      gen_random_uuid(), ${accountId}, ${companyId},
      (SELECT id FROM chart_of_accounts WHERE company_id = ${companyId} AND code = '7000'),
      (SELECT id FROM chart_of_accounts WHERE company_id = ${companyId} AND code = '1000'),
      42.00,
      (DATE '2026-01-01' + ((g % 350) || ' days')::interval)::date,
      'Supplier ' || (g % 50),
      now(), now()
    FROM generate_series(1, ${EXPENSE_COUNT}) g
  `);

  // THE LEDGER IS GENERATED BY THE REAL POSTING HELPERS, not by hand.
  //
  // The rows above are plain data and generate_series can invent them safely.
  // Journal lines are different: if the fixture hand-writes them, every timing
  // below measures a ledger shaped by this file's assumptions rather than by
  // the code under test, and a posting-shape change would not show up here at
  // all. So the entries come from invoicePostingLines / expensePostingLines —
  // the same pure functions the API posts through — exactly as
  // scripts/seed-load-test.ts does it.
  const coaRows = await db
    .select({ id: chartOfAccounts.id, code: chartOfAccounts.code })
    .from(chartOfAccounts)
    .where(eq(chartOfAccounts.companyId, companyId));
  const coaByCode = new Map(coaRows.map((r) => [r.code, r.id]));

  const invoiceRows = await db
    .select({ id: invoices.id, issueDate: invoices.issueDate, status: invoices.status })
    .from(invoices)
    .where(eq(invoices.companyId, companyId));
  const expenseRows = await db
    .select({ id: expenses.id, expenseDate: expenses.expenseDate, amount: expenses.amount })
    .from(expenses)
    .where(eq(expenses.companyId, companyId));

  type EntryRow = typeof journalEntries.$inferInsert;
  type LineRow = typeof journalLines.$inferInsert;
  const entries: EntryRow[] = [];
  const lines: LineRow[] = [];

  function pushEntry(
    sourceEntityType: string,
    sourceEntityId: string,
    postedAt: Date,
    memo: string,
    ledgerLines: { code: string; side: 'debit' | 'credit'; amount: string }[],
  ) {
    const kept = ledgerLines.filter((l) => Number(l.amount) > 0);
    if (kept.length < 2) return;
    const entryId = uuidv7();
    entries.push({
      id: entryId,
      accountId,
      companyId,
      sourceEntityType,
      sourceEntityId,
      postedAt,
      memo,
    });
    for (const l of kept) {
      const coaAccountId = coaByCode.get(l.code);
      if (!coaAccountId) throw new Error(`fixture: COA ${l.code} missing`);
      lines.push({
        id: uuidv7(),
        accountId,
        journalEntryId: entryId,
        coaAccountId,
        side: l.side,
        amount: l.amount,
      });
    }
  }

  for (const inv of invoiceRows) {
    // Half the line value is product, half service — matching the alternating
    // line types seeded above, so the revenue split is realistic.
    const amounts = {
      subtotal: '100.00',
      productSubtotal: '50.00',
      tax: '8.25',
      total: '108.25',
    };
    const postedAt = new Date(`${inv.issueDate}T00:00:00.000Z`);
    pushEntry(
      'invoice',
      inv.id,
      postedAt,
      'Invoice issued',
      invoicePostingLines('draft', 'sent', amounts),
    );
    if (inv.status === 'paid') {
      pushEntry(
        'invoice',
        inv.id,
        postedAt,
        'Invoice paid',
        invoicePostingLines('sent', 'paid', amounts),
      );
    }
  }
  for (const exp of expenseRows) {
    pushEntry(
      'expense',
      exp.id,
      new Date(`${exp.expenseDate}T00:00:00.000Z`),
      'Expense',
      expensePostingLines({ categoryCode: '7000', paymentCode: '1000', amount: exp.amount }),
    );
  }

  // ONE transaction around every batch, not a transaction per batch.
  //
  // The sum-to-zero trigger is DEFERRED to commit, and chunking by a fixed row
  // count splits an entry's lines across two commits — the first then sees an
  // entry holding only some of its legs and rightly rejects it. Batching is
  // only safe if the batches align with entry boundaries; wrapping the lot is
  // simpler and obviously correct, and the trigger fires once with everything
  // present. (Learned by doing it the other way first.)
  const CHUNK = 500;
  await db.transaction(async (tx) => {
    for (let i = 0; i < entries.length; i += CHUNK) {
      await tx.insert(journalEntries).values(entries.slice(i, i + CHUNK));
    }
    for (let i = 0; i < lines.length; i += CHUNK) {
      await tx.insert(journalLines).values(lines.slice(i, i + CHUNK));
    }
  });

  // ANALYZE, or the planner works from stale statistics and every timing below
  // measures a bad plan rather than the query.
  await db.execute(sql`ANALYZE`);
}

describe.skipIf(!SCALE)('reports at scale', () => {
  let ctx: {
    app: ReturnType<typeof createApp>;
    handle: ReturnType<typeof createApiDatabase>;
    companyId: string;
    headers: Record<string, string>;
  };
  let lineCount = 0;

  beforeAll(async () => {
    await resetDb();
    const { app, handle } = buildApp();
    const email = 'scale@test.com';
    const signRes = await app.request('/api/auth/sign-up/email', {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({ email, password: 'correct horse battery staple', name: email }),
    });
    if (signRes.status !== 200) throw new Error(`sign-up failed: ${signRes.status}`);
    const cookie = extractSessionCookie(signRes);

    const db = getTestDb();
    const [user] = await db
      .select({ id: authUser.id })
      .from(authUser)
      .where(eq(authUser.email, email));
    if (!user) throw new Error('user not seeded');
    const [m] = await db
      .select({ accountId: memberships.accountId })
      .from(memberships)
      .where(eq(memberships.userId, user.id));
    if (!m) throw new Error('membership not seeded');
    const [company] = await db
      .select({ id: companies.id })
      .from(companies)
      .where(eq(companies.accountId, m.accountId));
    if (!company) throw new Error('company not seeded');

    const started = Date.now();
    await seedLargeBook(m.accountId, company.id);
    const [{ count } = { count: 0 }] = await db
      .execute<{ count: number }>(sql`SELECT count(*)::int AS count FROM journal_lines`)
      .then((r) => r.rows);
    lineCount = Number(count);
    // biome-ignore lint/suspicious/noConsoleLog: the timing table IS this harness's output
    console.log(
      `\nseeded ${lineCount.toLocaleString()} journal lines in ${Date.now() - started}ms`,
    );

    ctx = {
      app,
      handle,
      companyId: company.id,
      headers: { cookie, 'x-account-id': m.accountId, 'content-type': 'application/json' },
    };
  }, 600_000);

  it('every report answers within budget on a large book', async () => {
    // Relative to the configured fixture size, so a smaller SCALE_INVOICES
    // override stays meaningful instead of failing an absolute floor.
    // Floor derived from the fixture: 4 lines per issued invoice (AR, service
    // revenue, product revenue, tax) + 2 per expense, so a smaller override stays
    // meaningful instead of failing an absolute threshold.
    expect(lineCount).toBeGreaterThan((INVOICE_COUNT * 4 + EXPENSE_COUNT * 2) * 0.9);

    const window = 'from=2026-01-01&to=2026-12-31';
    const targets: [string, string][] = [
      ['dashboard', `/api/companies/${ctx.companyId}/dashboard`],
      ['profit-loss', `/api/companies/${ctx.companyId}/profit-loss?${window}`],
      ['balance-sheet', `/api/companies/${ctx.companyId}/balance-sheet?asOf=2026-12-31`],
      ['ar-aging', `/api/companies/${ctx.companyId}/ar-aging`],
      ['sales-by-customer', `/api/companies/${ctx.companyId}/sales-by-customer?${window}`],
      ['revenue-over-time', `/api/companies/${ctx.companyId}/revenue-over-time?${window}`],
      ['top-products', `/api/companies/${ctx.companyId}/top-products?${window}`],
      ['sales-tax', `/api/companies/${ctx.companyId}/sales-tax?${window}`],
      ['schedule-c', `/api/companies/${ctx.companyId}/schedule-c?year=2026`],
      ['tax-worksheet', `/api/companies/${ctx.companyId}/tax-worksheet?year=2026`],
      ['estimate-win-rate', `/api/companies/${ctx.companyId}/estimate-win-rate?${window}`],
      ['job-margin', `/api/companies/${ctx.companyId}/job-margin?${window}`],
      ['spending-anomalies', `/api/companies/${ctx.companyId}/spending-anomalies`],
      // The list endpoints matter as much as the reports — they are what a user
      // hits first, and keyset pagination is the thing that has to hold up.
      ['invoices:list', '/api/invoices?limit=50'],
      ['expenses:list', '/api/expenses?limit=50'],
      ['contacts:list', '/api/contacts?limit=50'],
    ];

    const results: { name: string; ms: number; status: number }[] = [];
    for (const [name, path] of targets) {
      const started = Date.now();
      const res = await ctx.app.request(path, { headers: ctx.headers });
      const ms = Date.now() - started;
      // Drain the body — otherwise we time the query but not the serialisation,
      // and a report that returns 20k rows is slow precisely in that step.
      await res.text();
      results.push({ name, ms, status: res.status });
    }

    const table = results
      .map((r) => `  ${r.name.padEnd(22)} ${String(r.ms).padStart(6)}ms  (${r.status})`)
      .join('\n');
    // biome-ignore lint/suspicious/noConsoleLog: the timing table IS this harness's output
    console.log(`\n${lineCount.toLocaleString()} journal lines · budget ${BUDGET_MS}ms\n${table}`);

    // A non-2xx means the report did not run at all — a silent 500 would
    // otherwise look like the fastest endpoint in the table.
    const failed = results.filter((r) => r.status >= 400);
    expect(failed.map((f) => `${f.name}:${f.status}`)).toEqual([]);

    const overBudget = results.filter((r) => r.ms > BUDGET_MS);
    expect(
      overBudget.map((r) => `${r.name} took ${r.ms}ms`),
      `over the ${BUDGET_MS}ms budget`,
    ).toEqual([]);
  }, 600_000);
});
