-- Automated invoice reminders (TMC-189).
--
-- Adds the per-company schedule (off by default), the per-invoice opt-out, and
-- the send log that makes the sweep idempotent.
--
-- The RLS policy and the GRANTs at the bottom are NOT generated by drizzle-kit
-- and must be hand-written for every new tenant table. Without the policy the
-- table is readable across accounts; without the GRANTs the app's non-BYPASSRLS
-- role cannot touch it and every request 500s. Mirrors 0031_invoice_payments.
--
-- bigint rather than integer on the day offsets is squawk's int-exhaustion rule,
-- which the whole schema follows. A day offset will never need 64 bits.
SET search_path TO public;--> statement-breakpoint

CREATE TABLE "invoice_reminders" (
	"id" uuid PRIMARY KEY NOT NULL,
	"account_id" uuid NOT NULL,
	"company_id" uuid NOT NULL,
	"invoice_id" uuid NOT NULL,
	"offset_days" bigint NOT NULL,
	"sent_on" date NOT NULL,
	"outstanding" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "reminders_enabled" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "reminder_offsets" bigint[] DEFAULT '{-5,7}' NOT NULL;--> statement-breakpoint
ALTER TABLE "invoices" ADD COLUMN "reminders_opted_out" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "invoice_reminders" ADD CONSTRAINT "invoice_reminders_account_id_accounts_id_fk" FOREIGN KEY ("account_id") REFERENCES "public"."accounts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "invoice_reminders" ADD CONSTRAINT "invoice_reminders_company_id_companies_id_fk" FOREIGN KEY ("company_id") REFERENCES "public"."companies"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "invoice_reminders" ADD CONSTRAINT "invoice_reminders_invoice_id_invoices_id_fk" FOREIGN KEY ("invoice_id") REFERENCES "public"."invoices"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "invoice_reminders_invoice_offset_uq" ON "invoice_reminders" USING btree ("invoice_id","offset_days");--> statement-breakpoint
CREATE INDEX "invoice_reminders_account_invoice_idx" ON "invoice_reminders" USING btree ("account_id","invoice_id");--> statement-breakpoint

ALTER TABLE "invoice_reminders" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE POLICY "invoice_reminders_tenant_isolation" ON "invoice_reminders" USING ((account_id = (NULLIF(current_setting('app.current_account_id'::text, true), ''::text))::uuid)) WITH CHECK ((account_id = (NULLIF(current_setting('app.current_account_id'::text, true), ''::text))::uuid));--> statement-breakpoint
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "invoice_reminders" TO thalermark_app;--> statement-breakpoint
GRANT SELECT ON TABLE "invoice_reminders" TO thalermark_staff_readonly;
