-- Global search (TMC-198).
--
-- A denormalized projection of the seven searchable entities (invoice,
-- estimate, contact, expense, bill, job, item) into one table, so search is one
-- indexed scan rather than an ILIKE fan-out across six tables.
--
-- The extensions at the top and the RLS policy, GRANTs and function at the
-- bottom are NOT generated by drizzle-kit and must be hand-written. Without the
-- policy the table is readable across accounts; without the GRANTs the app's
-- non-BYPASSRLS role cannot touch it and every request 500s. Mirrors
-- 0033_invoice_reminders. Everything between is generated -- regenerate with
-- `pnpm drizzle:generate --name search_documents` and re-apply the two ends.
--
-- WHY THE SECURITY DEFINER FUNCTION EXISTS. No text-matching operator in PG 17
-- is leakproof (texticlike, ts_match_vq, ts_rank and the trigram ops are all
-- proleakproof=f; only texteq/uuid_eq/int8eq are true). Postgres will not
-- evaluate a non-leakproof qual before an RLS policy qual, so under RLS the GIN
-- index can never become an index condition and `tsv @@ q` degrades to a filter
-- over every row in the account. Measured: 1.76ms indexed vs 11.56ms filtered
-- at 100k documents, and 11.6ms vs 44.2ms for the trigram pass. Full evidence,
-- including the cross-tenant and fail-closed tests, in
-- spikes/SEARCH-RLS-INDEX.md.
--
-- WHY THE INDEXES LEAD WITH account_id. A plain gin(tsv) on a multi-tenant
-- table is tenant-blind: its scan cost tracks how many rows match the term
-- across EVERY tenant, then account_id filters the heap fetches. btree_gin lets
-- account_id lead, so the scan narrows by tenant and term in one pass. It is
-- also smaller than the plain index (11MB vs 15MB at 330k rows), because
-- leading with the tenant clusters the posting lists.
--
-- No backfill here. migrate.ts runs every pending migration in ONE transaction
-- at boot; projecting every tenant would block startup for as long as the
-- largest install takes. The search-reindex pg-boss job fills the table, and a
-- one-shot is enqueued on boot.
SET search_path TO public;--> statement-breakpoint

CREATE EXTENSION IF NOT EXISTS pg_trgm;--> statement-breakpoint
CREATE EXTENSION IF NOT EXISTS btree_gin;--> statement-breakpoint

CREATE TABLE "search_documents" (
	"entity_type" text NOT NULL,
	"entity_id" uuid NOT NULL,
	"account_id" uuid NOT NULL,
	"company_id" uuid NOT NULL,
	"title" text NOT NULL,
	"subtitle" text,
	"title_norm" text NOT NULL,
	"ref_norm" text,
	"subtitle_norm" text,
	"body_norm" text,
	"status" text,
	"amount_cents" bigint,
	"occurred_on" date,
	"entity_updated_at" timestamp with time zone NOT NULL,
	"indexed_at" timestamp with time zone DEFAULT now() NOT NULL,
	"tsv" "tsvector" GENERATED ALWAYS AS (setweight(to_tsvector('simple'::regconfig, coalesce("title_norm", '')), 'A') || setweight(to_tsvector('simple'::regconfig, coalesce("ref_norm", '')), 'A') || setweight(to_tsvector('simple'::regconfig, coalesce("subtitle_norm", '')), 'B') || setweight(to_tsvector('simple'::regconfig, coalesce("body_norm", '')), 'C')) STORED,
	CONSTRAINT "search_documents_pkey" PRIMARY KEY("entity_type","entity_id")
);
--> statement-breakpoint
ALTER TABLE "search_documents" ADD CONSTRAINT "search_documents_account_id_accounts_id_fk" FOREIGN KEY ("account_id") REFERENCES "public"."accounts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "search_documents" ADD CONSTRAINT "search_documents_company_id_companies_id_fk" FOREIGN KEY ("company_id") REFERENCES "public"."companies"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "search_documents_account_tsv_idx" ON "search_documents" USING gin ("account_id","tsv");--> statement-breakpoint
CREATE INDEX "search_documents_account_title_trgm_idx" ON "search_documents" USING gin ("account_id","title_norm" gin_trgm_ops);--> statement-breakpoint
CREATE INDEX "search_documents_account_updated_idx" ON "search_documents" USING btree ("account_id","entity_updated_at" DESC NULLS LAST,"entity_id" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "search_documents_account_amount_idx" ON "search_documents" USING btree ("account_id","amount_cents") WHERE "search_documents"."amount_cents" IS NOT NULL;--> statement-breakpoint
CREATE INDEX "search_documents_account_company_idx" ON "search_documents" USING btree ("account_id","company_id");--> statement-breakpoint

ALTER TABLE "search_documents" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE POLICY "search_documents_tenant_isolation" ON "search_documents" USING ((account_id = (NULLIF(current_setting('app.current_account_id'::text, true), ''::text))::uuid)) WITH CHECK ((account_id = (NULLIF(current_setting('app.current_account_id'::text, true), ''::text))::uuid));--> statement-breakpoint
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "search_documents" TO thalermark_app;--> statement-breakpoint
GRANT SELECT ON TABLE "search_documents" TO thalermark_staff_readonly;--> statement-breakpoint

-- Search's index path. See the header for why this cannot be a plain query.
--
-- SAFETY CONTRACT, in order of importance:
--   1. account_id is read from the SAME GUC the RLS policy reads, never taken
--      as an argument. A caller cannot ask for another tenant. Unset => RAISE,
--      never "return everything".
--   2. Returns keys and a score only. No row content leaves this function, so a
--      bug leaks at most the existence and ranking of opaque ids.
--   3. The caller re-reads rows by primary key THROUGH RLS. That is the fence;
--      this function is an accelerator, not a bypass. An id it should not have
--      returned simply fails to join.
--   4. search_path is pinned, every input is a bound typed parameter, there is
--      no dynamic SQL, and EXECUTE is revoked from PUBLIC.
--
-- The owner is the migration role (thalermark), which is a superuser -- more
-- privilege than this needs. The contract above is what contains it. Moving
-- ownership to a dedicated non-superuser role owning only search_documents is a
-- worthwhile hardening follow-up.
--
-- Three passes rather than one OR: a single
--   WHERE tsv @@ q OR amount_cents = $2 OR title_norm % $3
-- forces a BitmapOr across three index types with wildly different
-- selectivities and the planner misestimates it. Three LIMITed passes each get
-- a correct plan, and the caller can skip the trigram pass entirely when the
-- tsquery pass already saturated the limit.
CREATE FUNCTION search_documents_match(
	p_query tsquery,
	p_trgm text,
	p_amount_cents bigint,
	p_company_id uuid,
	p_types text[],
	p_limit integer
) RETURNS TABLE (entity_type text, entity_id uuid, score real)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
PARALLEL SAFE
SET search_path = pg_catalog, public
SET pg_trgm.similarity_threshold = '0.3'
AS $$
DECLARE
	v_account uuid;
BEGIN
	v_account := NULLIF(current_setting('app.current_account_id', true), '')::uuid;
	IF v_account IS NULL THEN
		RAISE EXCEPTION 'search: no account context';
	END IF;

	RETURN QUERY
	WITH ts AS (
		SELECT d.entity_type, d.entity_id, (2.0 + ts_rank_cd(d.tsv, p_query))::real AS score
		FROM search_documents d
		WHERE p_query IS NOT NULL
		  AND d.account_id = v_account
		  AND d.tsv @@ p_query
		  AND (p_company_id IS NULL OR d.company_id = p_company_id)
		  AND (p_types IS NULL OR d.entity_type = ANY(p_types))
		ORDER BY 3 DESC, d.entity_updated_at DESC, d.entity_id DESC
		LIMIT p_limit
	),
	amt AS (
		SELECT d.entity_type, d.entity_id, 2.5::real AS score
		FROM search_documents d
		WHERE p_amount_cents IS NOT NULL
		  AND d.account_id = v_account
		  AND d.amount_cents = p_amount_cents
		  AND (p_company_id IS NULL OR d.company_id = p_company_id)
		  AND (p_types IS NULL OR d.entity_type = ANY(p_types))
		ORDER BY d.entity_updated_at DESC, d.entity_id DESC
		LIMIT p_limit
	),
	trgm AS (
		SELECT d.entity_type, d.entity_id, similarity(d.title_norm, p_trgm)::real AS score
		FROM search_documents d
		WHERE p_trgm IS NOT NULL
		  AND d.account_id = v_account
		  AND d.title_norm % p_trgm
		  AND (p_company_id IS NULL OR d.company_id = p_company_id)
		  AND (p_types IS NULL OR d.entity_type = ANY(p_types))
		ORDER BY 3 DESC, d.entity_updated_at DESC, d.entity_id DESC
		LIMIT p_limit
	)
	SELECT u.entity_type, u.entity_id, max(u.score) AS score
	FROM (SELECT * FROM ts UNION ALL SELECT * FROM amt UNION ALL SELECT * FROM trgm) u
	GROUP BY u.entity_type, u.entity_id
	ORDER BY 3 DESC, u.entity_id DESC
	LIMIT p_limit;
END;
$$;--> statement-breakpoint
REVOKE ALL ON FUNCTION search_documents_match(tsquery, text, bigint, uuid, text[], integer) FROM PUBLIC;--> statement-breakpoint
GRANT EXECUTE ON FUNCTION search_documents_match(tsquery, text, bigint, uuid, text[], integer) TO thalermark_app;