#!/usr/bin/env node
// Catch a breaking API change before it ships, without being told about it.
//
// Web and mobile both consume the api over @thalermark/api-contract, and no
// route is version-prefixed. So a newer api has to keep serving older clients,
// and the client most at risk is a phone: it can be months old and may never be
// updated. The rule that keeps that working is additive-only — responses may
// gain fields, never lose or rename them; new request fields are always
// optional.
//
// A rule you have to remember is a rule you eventually break, so this checks it
// mechanically. The Hono RPC types already describe every route's request and
// response precisely; this expands them with the TypeScript checker, writes the
// result to a committed snapshot, and compares. Additive changes update the
// snapshot silently. Breaking ones fail, and have to be declared.
//
// Only success responses are recorded. Error bodies carry Zod's internal issue
// types, which churn on any Zod upgrade and would drown the real signal.
//
//   pnpm contract:check            fail if the contract broke; absorb safe changes
//   pnpm contract:check --update   accept the current contract as the baseline
//   pnpm contract:check --frozen   fail on ANY drift without writing (CI)
//   pnpm contract:check --json     machine-readable, used by scripts/release.mjs

import { execFileSync } from 'node:child_process';
import { readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import ts from 'typescript';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const INDEX = join(ROOT, 'packages/api-contract/src/index.ts');
const PROBE = join(ROOT, 'packages/api-contract/src/__contract-probe.ts');
const SNAPSHOT = join(ROOT, 'packages/api-contract/contract.snapshot.json');
const MAX_DEPTH = 8;

// Every XAppType re-exported by the contract package. Read from the AST rather
// than a hand-kept list so a new domain is covered the day it is exported.
function appTypeNames() {
  const source = ts.createSourceFile(
    'index.ts',
    readFileSync(INDEX, 'utf8'),
    ts.ScriptTarget.Latest,
    true,
  );
  const names = [];
  ts.forEachChild(source, (node) => {
    if (!ts.isExportDeclaration(node) || !node.exportClause) return;
    if (!ts.isNamedExports(node.exportClause)) return;
    for (const element of node.exportClause.elements) {
      if (element.name.text.endsWith('AppType')) names.push(element.name.text);
    }
  });
  return names.sort();
}

function probeSource(names) {
  return [
    '// Generated by scripts/contract-check.mjs. Deleted on exit; never committed.',
    "import type { ExtractSchema } from 'hono/types';",
    `import type { ${names.join(', ')} } from './index.js';`,
    ...names.map((name) => `export type P_${name} = ExtractSchema<${name}>;`),
    '',
  ].join('\n');
}

// Anything the checker can describe in one line is a leaf. Without this the
// walk descends into String.prototype and a two-field response serializes as
// forty thousand lines of `charCodeAt`.
const LEAF_FLAGS =
  ts.TypeFlags.Any |
  ts.TypeFlags.Unknown |
  ts.TypeFlags.String |
  ts.TypeFlags.Number |
  ts.TypeFlags.Boolean |
  ts.TypeFlags.BigInt |
  ts.TypeFlags.StringLiteral |
  ts.TypeFlags.NumberLiteral |
  ts.TypeFlags.BooleanLiteral |
  ts.TypeFlags.BigIntLiteral |
  ts.TypeFlags.ESSymbol |
  ts.TypeFlags.UniqueESSymbol |
  ts.TypeFlags.Void |
  ts.TypeFlags.Undefined |
  ts.TypeFlags.Null |
  ts.TypeFlags.Never |
  ts.TypeFlags.Enum |
  ts.TypeFlags.EnumLiteral |
  ts.TypeFlags.TypeParameter |
  ts.TypeFlags.NonPrimitive;

function arrayElement(checker, type) {
  const symbol = type.getSymbol?.();
  if (!symbol) return null;
  const name = symbol.getName();
  if (name !== 'Array' && name !== 'ReadonlyArray') return null;
  const args = checker.getTypeArguments(type);
  return args?.length === 1 ? args[0] : null;
}

// Date, Map, Promise and friends are structural noise for a wire contract, and
// their surface changes with the TypeScript lib rather than with our api.
function isBuiltIn(program, type) {
  const declarations = type.getSymbol?.()?.getDeclarations?.() ?? [];
  return declarations.some((declaration) =>
    program.isSourceFileDefaultLibrary(declaration.getSourceFile()),
  );
}

// A stable, diffable description of a type. Objects become sorted key maps with
// '?' marking optional; arrays become one-element lists; anything without
// properties is a leaf and keeps its printed form.
function normalize(ctx, type, depth = 0, seen = new Set()) {
  const { checker, program } = ctx;
  if (depth > MAX_DEPTH) return '(depth limit)';
  if (type.isUnion()) {
    const members = type.types.map((member) => normalize(ctx, member, depth, seen));
    const unique = [...new Set(members.map((m) => JSON.stringify(m)))].sort();
    return unique.length === 1
      ? JSON.parse(unique[0])
      : { union: unique.map((m) => JSON.parse(m)) };
  }
  if (type.flags & LEAF_FLAGS) return checker.typeToString(type);
  if (checker.getSignaturesOfType(type, ts.SignatureKind.Call).length) {
    return checker.typeToString(type);
  }
  const element = arrayElement(checker, type);
  if (element) return [normalize(ctx, element, depth + 1, seen)];
  if (isBuiltIn(program, type)) return checker.typeToString(type);
  const props = checker.getPropertiesOfType(type);
  if (!props.length) return checker.typeToString(type);
  if (seen.has(type)) return '(recursive)';
  const nested = new Set(seen).add(type);
  const shape = {};
  for (const prop of [...props].sort((a, b) => a.name.localeCompare(b.name))) {
    const optional = (prop.flags & ts.SymbolFlags.Optional) !== 0;
    const key = optional ? `${prop.name}?` : prop.name;
    shape[key] = normalize(ctx, checker.getTypeOfSymbol(prop), depth + 1, nested);
  }
  return shape;
}

// c.json(x) with no explicit status widens to ContentfulStatusCode; anything
// else that is 2xx is also a success. Explicit 4xx/5xx variants are dropped.
function isSuccess(statusText) {
  if (statusText.includes('ContentfulStatusCode')) return true;
  return statusText
    .split('|')
    .map((part) => part.trim())
    .some((part) => /^2\d\d$/.test(part));
}

function buildContract() {
  const names = appTypeNames();
  writeFileSync(PROBE, probeSource(names));
  try {
    const { config } = ts.readConfigFile(join(ROOT, 'tsconfig.base.json'), (p) =>
      readFileSync(p, 'utf8'),
    );
    const { options } = ts.convertCompilerOptionsFromJson(config.compilerOptions ?? {}, ROOT);
    const program = ts.createProgram([PROBE], { ...options, noEmit: true });
    const checker = program.getTypeChecker();
    const ctx = { checker, program };
    const source = program.getSourceFile(PROBE);
    const routes = {};

    ts.forEachChild(source, (node) => {
      if (!ts.isTypeAliasDeclaration(node) || !node.name.text.startsWith('P_')) return;
      const schema = checker.getTypeAtLocation(node.name);
      for (const route of checker.getPropertiesOfType(schema)) {
        for (const method of checker.getPropertiesOfType(checker.getTypeOfSymbol(route))) {
          const methodType = checker.getTypeOfSymbol(method);
          const variants = methodType.isUnion() ? methodType.types : [methodType];
          for (const variant of variants) {
            const statusSymbol = checker.getPropertyOfType(variant, 'status');
            const status = statusSymbol
              ? checker.typeToString(checker.getTypeOfSymbol(statusSymbol))
              : '';
            if (!isSuccess(status)) continue;
            const inputSymbol = checker.getPropertyOfType(variant, 'input');
            const outputSymbol = checker.getPropertyOfType(variant, 'output');
            routes[`${method.name} ${route.name}`] = {
              request: inputSymbol ? normalize(ctx, checker.getTypeOfSymbol(inputSymbol)) : {},
              response: outputSymbol ? normalize(ctx, checker.getTypeOfSymbol(outputSymbol)) : {},
            };
          }
        }
      }
    });
    return {
      routes: Object.fromEntries(Object.entries(routes).sort(([a], [b]) => a.localeCompare(b))),
    };
  } finally {
    rmSync(PROBE, { force: true });
  }
}

function fieldsOf(shape) {
  const map = new Map();
  if (!shape || typeof shape !== 'object' || Array.isArray(shape) || shape.union) return map;
  for (const [key, value] of Object.entries(shape)) {
    const optional = key.endsWith('?');
    map.set(optional ? key.slice(0, -1) : key, { optional, shape: value });
  }
  return map;
}

const truncate = (value) => {
  const text = typeof value === 'string' ? value : JSON.stringify(value);
  return text.length > 80 ? `${text.slice(0, 77)}...` : text;
};

// Direction matters. A response may gain fields (old clients ignore them) but
// never lose one or turn it optional. A request may gain optional fields and
// drop fields (the server ignores what it no longer reads) but a new required
// field breaks every client that does not know to send it.
function diffShape(before, after, path, kind, findings) {
  const beforeFields = fieldsOf(before);
  const afterFields = fieldsOf(after);

  if (beforeFields.size || afterFields.size) {
    for (const [name, prev] of beforeFields) {
      const at = path ? `${path}.${name}` : name;
      const next = afterFields.get(name);
      if (!next) {
        if (kind === 'response') findings.push(`response field removed: ${at}`);
        continue;
      }
      if (kind === 'response' && !prev.optional && next.optional) {
        findings.push(`response field is no longer always present: ${at}`);
      }
      if (kind === 'request' && prev.optional && !next.optional) {
        findings.push(`request field became required: ${at}`);
      }
      diffShape(prev.shape, next.shape, at, kind, findings);
    }
    for (const [name, next] of afterFields) {
      if (beforeFields.has(name)) continue;
      if (kind === 'request' && !next.optional) {
        findings.push(`new required request field: ${path ? `${path}.${name}` : name}`);
      }
    }
    return;
  }

  if (Array.isArray(before) && Array.isArray(after)) {
    diffShape(before[0], after[0], `${path}[]`, kind, findings);
    return;
  }

  const a = JSON.stringify(before);
  const b = JSON.stringify(after);
  if (a !== b)
    findings.push(
      `${kind} type changed at ${path || '(root)'}: ${truncate(before)} -> ${truncate(after)}`,
    );
}

function compare(before, after) {
  const breaking = [];
  const additive = [];
  for (const [route, prev] of Object.entries(before.routes)) {
    const next = after.routes[route];
    if (!next) {
      breaking.push({ route, detail: 'route removed' });
      continue;
    }
    const findings = [];
    diffShape(prev.response, next.response, '', 'response', findings);
    diffShape(prev.request, next.request, '', 'request', findings);
    for (const detail of findings) breaking.push({ route, detail });
  }
  for (const route of Object.keys(after.routes)) {
    if (!before.routes[route]) additive.push({ route, detail: 'route added' });
  }
  return { breaking, additive };
}

// How much of the mutating surface declares a JSON body. Counts a typed `json`
// specifically: a route with a path param has a request object either way, so
// "is the request an object" would call `/api/x/:id` covered while its body was
// still invisible. That mistake is why this was first reported as 89/118.
function coverage(contract) {
  const mutating = Object.entries(contract.routes).filter(([key]) =>
    /^\$(post|patch|put|delete)/.test(key),
  );
  const typed = mutating.filter(
    ([, value]) => value.request && typeof value.request === 'object' && 'json' in value.request,
  );
  return { mutating: mutating.length, typed: typed.length };
}

// A body read with a bare `await c.req.json()` never enters Hono's type system,
// so its shape is invisible here and a new required field on it is not caught.
// TMC-292 moved every such route onto validator(); this stops one coming back.
//
// An exemption exists because validator('json') cannot express an OPTIONAL body:
// a POST carrying a JSON content-type and no body at all is "malformed" to it,
// which is precisely how a client starts a timer with no note. Such a route may
// keep the raw read by carrying a `contract-check-exempt:` comment saying why.
// Exemptions are counted and printed rather than hidden, because a blind spot
// you cannot see is worse than one you can.
//
// Webhook routes that must hash the unparsed body use c.req.text() and are
// deliberately unaffected by any of this.
function rawBodyReads() {
  const dir = join(ROOT, 'apps/api/src/routes');
  const blocking = [];
  const exempt = [];
  for (const file of readdirSync(dir)) {
    if (!file.endsWith('.ts') || file.endsWith('.test.ts')) continue;
    const lines = readFileSync(join(dir, file), 'utf8').split('\n');
    lines.forEach((line, i) => {
      if (!line.includes('c.req.json()')) return;
      const nearby = lines.slice(Math.max(0, i - 10), i).join('\n');
      const where = `apps/api/src/routes/${file}:${i + 1}`;
      (nearby.includes('contract-check-exempt') ? exempt : blocking).push(where);
    });
  }
  return { blocking, exempt };
}

function main() {
  const args = process.argv.slice(2);
  const update = args.includes('--update');
  const asJson = args.includes('--json');
  // CI must not fix things up silently: it verifies the committed snapshot is
  // the one this code produces, the same way a lockfile check works.
  const frozen = args.includes('--frozen');

  const raw = rawBodyReads();
  if (raw.blocking.length && !asJson) {
    console.error(`
  ${raw.blocking.length} route(s) read the request body with a bare c.req.json(), so
  their shape never reaches the contract and a new required field there is not
  caught:

${raw.blocking.map((hit) => `    ${hit}`).join('\n')}

  Put the body through validator('json', ...) instead. If the route needs the
  unparsed body (webhook signatures) use c.req.text(); if its body is genuinely
  optional, add a 'contract-check-exempt:' comment saying so.
`);
    process.exit(1);
  }

  const current = buildContract();
  const routeCount = Object.keys(current.routes).length;

  let baseline = null;
  try {
    baseline = JSON.parse(readFileSync(SNAPSHOT, 'utf8'));
  } catch {
    baseline = null;
  }

  if (!baseline) {
    if (frozen) {
      console.error(
        '\n  No contract snapshot committed. Run `pnpm contract:check` and commit it.\n',
      );
      process.exit(1);
    }
    writeFileSync(SNAPSHOT, `${JSON.stringify(current, null, 2)}\n`);
    const { mutating, typed } = coverage(current);
    if (asJson) console.log(JSON.stringify({ seeded: true, breaking: [], routeCount }));
    else {
      console.log(`\n  Contract baseline written: ${routeCount} routes.`);
      console.log(`  ${typed}/${mutating} mutating routes declare a JSON body.\n`);
    }
    return;
  }

  const { breaking, additive } = compare(baseline, current);

  if (frozen && !breaking.length) {
    const serialized = `${JSON.stringify(current, null, 2)}\n`;
    if (serialized !== readFileSync(SNAPSHOT, 'utf8')) {
      console.error(`
  The committed contract snapshot is out of date. Nothing breaking, but it has
  drifted from what the code now produces. Run:

      pnpm contract:check

  and commit packages/api-contract/contract.snapshot.json.
`);
      process.exit(1);
    }
    console.log(`\n  Contract snapshot current: ${routeCount} routes.\n`);
    return;
  }

  if (asJson) {
    console.log(JSON.stringify({ breaking, additive, routeCount, rawBodyReads: rawBodyReads() }));
    process.exit(breaking.length && !update ? 1 : 0);
  }

  if (!breaking.length) {
    // Additive changes are safe by definition, so the snapshot just moves with
    // them; no reason to make anyone run --update for a change that cannot hurt.
    writeFileSync(SNAPSHOT, `${JSON.stringify(current, null, 2)}\n`);
    const { mutating, typed } = coverage(current);
    console.log(
      `\n  Contract OK: ${routeCount} routes, ${additive.length} added, nothing breaking.`,
    );
    console.log(`  ${typed}/${mutating} mutating routes declare a JSON body; the rest take none.`);
    if (raw.exempt.length) {
      console.log(
        `  ${raw.exempt.length} exempt (optional body, still unchecked): ${raw.exempt.join(', ')}`,
      );
    }
    console.log('');
    return;
  }

  if (update) {
    writeFileSync(SNAPSHOT, `${JSON.stringify(current, null, 2)}\n`);
    console.log(
      `\n  Snapshot updated over ${breaking.length} breaking change(s). Declare them in the commit.\n`,
    );
    return;
  }

  console.error(`\n  BREAKING API CHANGE (${breaking.length})\n`);
  const byRoute = new Map();
  for (const { route, detail } of breaking) {
    if (!byRoute.has(route)) byRoute.set(route, []);
    byRoute.get(route).push(detail);
  }
  for (const [route, details] of byRoute) {
    console.error(`  ${route}`);
    for (const detail of details) console.error(`      ${detail}`);
  }
  console.error(`
  Old web builds and installed phone apps read this contract. Removing or
  renaming a response field, or requiring a new request field, breaks them.

  If this is unintentional, keep the old field and add the new one beside it.
  If it is deliberate, record it:

      pnpm contract:check --update

  and mark the commit breaking (a '!' after the type, or a BREAKING CHANGE
  trailer) so the release picks it up as a major.
`);
  process.exit(1);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) main();
